<?php

/**
 * @file
 * Contains charts_api_example.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function charts_api_example_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the charts_api_example module.
    case 'help.page.charts_api_example':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('How to interact with the Charts Api') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function charts_api_example_theme() {
  return [
    'charts_api_example' => [
      'template' => 'charts_api_example',
      'variables' => array('test_var' => ''),
    ],
  ];
}

function charts_api_example_preprocess_page(&$variables){
  $variables['naam'] = 'Kittobbe';
  $variables['test_var'] = 'Kittobbe test_var';
}